version: '3.3'
services:
  elasticsearch:
    image: 'elasticsearch:7.9.3'
    restart: unless-stopped
    volumes:
      - './elasticsearch/data:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    networks:
      - elk
  kibana:
    image: 'kibana:7.9.3'
    restart: unless-stopped
    ports:
      - '5601:5601'
    links:
      - 'elasticsearch:elasticsearch'
    environment:
      - 'elasticsearch.hosts=http://elasticsearch:9200'
    networks:
      - elk
  logstash:
    image: 'logstash:7.9.3'
    restart: unless-stopped
    volumes:
      - './logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml'
      - './logstash/config/pipelines:/usr/share/logstash/config/pipelines'
    ports:
      - '5046:5046'
      - '5044:5044'
      - '9600:9600'
    environment:
      - XPACK_MONITORING_ENABLED=false
    networks:
      - elk
networks:
  elk:
    driver: bridge
